# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :to_internal_testing do
    supply(
      track: "internal",
      json_key: "./.google-play/gitapower-service-account.json",
      apk: "../build/app/outputs/apk/release/app-release.apk"
    )
  end
end
