
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :to_internal_testing do
    supply(
      track: "internal",
      json_key: "./.google-play/gitapower-service-account.json",
      apk: "../build/app/outputs/apk/release/app-release.apk"
    )
  end
end
