name: askys
description: A new beginning.

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.17.6 <3.4.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.0
  card_settings: ^3.5.0
  markdown: ^7.2.2
  stack: ^0.2.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  firebase_crashlytics: ^3.4.18
  firebase_core: ^2.27.1
  shared_preferences: 2.2.2
  enum_to_string:
  float_column: 2.1.5
  drop_cap_text:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_cov_console: ^0.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - gita-begin/compile/
    - gita-begin/gita/
    - google_fonts/
  fonts:
    - family: Caveat
      fonts:
        - asset: google_fonts/Caveat-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/lordfeet.png"
  web:
    generate: true
    image_path: "images/lordfeet.png"

  assets:
    - images/
