const headers = {
  'Back-to-Basics.md': '''Translation guide''',
  'Chapter_1.md': '''Doubt and worry''',
  'Chapter_2.md': '''Do it for Krishna''',
  'Chapter_3.md': '''Worship happens''',
  'Chapter_4.md': '''Worship with activity''',
  'Chapter_5.md': '''Offer your work''',
  'Chapter_6.md': '''Intimacy with Krishna''',
  'Chapter_7.md': '''Types of worshipers''',
  'Chapter_8.md': '''Know Lord Krishna''',
  'Chapter_9.md': '''Worship with devotion''',
  'Chapter_10.md': '''Krishna is special''',
  'Chapter_11.md': '''Show me Krishna''',
  'Chapter_12.md': '''Aspire to adore''',
  'Chapter_13.md': '''Devotion in this world''',
  'Chapter_14.md': '''Obstacles''',
  'Chapter_15.md': '''Awareness''',
  'Chapter_16.md': '''Regard instructions''',
  'Chapter_17.md': '''Devotion on purpose''',
  'Chapter_18.md': '''Surrender''',
};
