// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn9Z9BamvMFnzuH-t6v_t8INKy7YBAFiU',
    appId: '1:351092704696:android:8554f54bbe4f9069e77b4d',
    messagingSenderId: '351092704696',
    projectId: 'gitapower',
    storageBucket: 'gitapower.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIq1EbrAEtzo8qYGT_j9dF_kNr484276M',
    appId: '1:351092704696:ios:0402ffc077caccf2e77b4d',
    messagingSenderId: '351092704696',
    projectId: 'gitapower',
    storageBucket: 'gitapower.firebasestorage.app',
    iosBundleId: 'com.gita.sudeep.gitahtml',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIq1EbrAEtzo8qYGT_j9dF_kNr484276M',
    appId: '1:351092704696:ios:0402ffc077caccf2e77b4d',
    messagingSenderId: '351092704696',
    projectId: 'gitapower',
    storageBucket: 'gitapower.firebasestorage.app',
    iosBundleId: 'com.gita.sudeep.gitahtml',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0-MmM5D-fKL9tq219ToVHQ4qRXNDlldc',
    appId: '1:351092704696:web:9f5784bf8d4b3dffe77b4d',
    messagingSenderId: '351092704696',
    projectId: 'gitapower',
    authDomain: 'gitapower.firebaseapp.com',
    storageBucket: 'gitapower.firebasestorage.app',
    measurementId: 'G-FVWXZKXT0W',
  );

}