import 'package:askys/choice_selector.dart';
import 'package:askys/choices_row.dart';
import 'package:askys/content_themes.dart';
import 'package:askys/content_widget.dart';
import 'package:askys/feedcontent.dart';
import 'package:askys/feedplay_icon.dart';
import 'package:askys/moving_subtitles.dart';
import 'package:askys/screenify.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class GuidedTourController extends GetxController {
  PageController pageTurner = PageController();
  PageController followTurner = PageController();
  List<CarouselController> showWordsScroller = [
    CarouselController(initialItem: 1),
    CarouselController(initialItem: 1),
    CarouselController(initialItem: 1),
  ];
  final mdLinksOfPages = <String>[].obs;
  void moveTo(TourState state, int stopIndex) {
    if (state == TourState.playing) {
      if (pageTurner.hasClients && mdLinksOfPages.isNotEmpty) {
        final Tour tour = Get.find<FeedContent>().tour;
        if (stopIndex == 0) {
          pageTurner.jumpToPage(0); // go to cover page
        } else if (tour.tourStops[stopIndex].link != null) {
          final pageIndex = mdLinksOfPages.indexWhere((link) => link == tour.tourStops[stopIndex].link) +
              1; // add 1 for the cover
          pageTurner.animateToPage(pageIndex,
              duration: const Duration(milliseconds: 250), curve: Curves.easeInOut);
        }
      }
    }
  }

  @override
  void onInit() {
    super.onInit();
    initTour();
  }

  void initTour() {
    final Tour tour = Get.find<FeedContent>().tour;
    tour.state.listen((_) => moveTo(tour.state.value, tour.stopIndex.value));
    tour.stopIndex.listen((_) => moveTo(tour.state.value, tour.stopIndex.value));
    void fillLinksOfPages(_) {
      mdLinksOfPages.value = tour.tourStops.where((s) => s.link != null).map((s) => s.link!).toList();
    }

    fillLinksOfPages(true);
    tour.tourStops.listen(fillLinksOfPages);
  }
}

Widget guidedTourScreen(String tourFolder) {
  Get.find<GuidedTourController>().initTour();
  return Obx(() {
    final PlayablesTOC playablesTOC = Get.find();
    final nullPlayable = Playable('', '', '');
    final playable =
        playablesTOC.playables.firstWhere((p) => p.tourFolder == tourFolder, orElse: () => nullPlayable);
    if (playable != nullPlayable) {
      return screenify(GuidedTourWidget(playable),
          appBar: AppBar(
            title: Text(
              playable.title,
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
          ),
          choicesRow: choicesRow([SizedBox(width: choiceSpacing), widgetToHome()],
              const [PersonalizeIcon(), SizedBox(width: choiceSpacing)]));
    } else {
      return screenify(const Text('Loading tour...'));
    }
  });
}

class GuidedTourWidget extends StatelessWidget {
  const GuidedTourWidget(this.playable, {super.key});
  final Playable playable;

  @override
  Widget build(context) {
    return Column(children: [
      FollowAlongWidget(),
      MovingSubtitles(),
      ShlokaSet(),
    ]);
  }
}

class FollowAlongWidget extends StatelessWidget {
  const FollowAlongWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Obx(() => Container(
          padding: EdgeInsets.symmetric(horizontal: 16),
          color: Theme.of(context).scaffoldBackgroundColor,
          child: Row(
            children: [
              FeedPlayIcon(key: const Key('guided/feedplay')),
              SizedBox(width: 12),
              Expanded(
                child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                  LinearProgressIndicator(value: computeProgress(), color: Colors.deepPurple),
                  const Text('Voice generated by AI', style: TextStyle(fontSize: 6, color: Colors.grey))
                ]),
              ),
            ],
          ),
        ));
  }

  double computeProgress() {
    FeedContent feedContent = Get.find();
    return feedContent.tour.tourStops.isNotEmpty && feedContent.tour.state.value != TourState.idle
        ? (feedContent.tour.stopIndex.value + 1) / feedContent.tour.tourStops.length
        : 0.0;
  }
}

class ShlokaSet extends StatelessWidget {
  const ShlokaSet({super.key});

  @override
  Widget build(BuildContext context) {
    final GuidedTourController guidedTourController = Get.find();
    final mdLinksOfPages = guidedTourController.mdLinksOfPages;
    return Obx(() => Expanded(
            child: PageView(
          controller: guidedTourController.pageTurner,
          children: [tourCover()] + mdLinksOfPages.map(oneShloka).toList(),
        )));
  }

  Widget oneShloka(String link, {Key? oneShlokaKey}) {
    final parts = link.split('/');
    final mdFilename = parts[0];
    final initialAnchor = parts.length > 1 ? parts[1] : null;
    return buildContent(mdFilename,
        initialAnchor: initialAnchor, onTap: () => Get.toNamed('/shloka/$mdFilename'), key: oneShlokaKey);
  }
}

Widget tourCover() {
  FeedContent feedContent = Get.find();
  return Obx(() {
    final List<List<String>> showsForThreeShlokas = [[], [], []];
    int currentShloka = -1;
    for (var tourStop in feedContent.tour.tourStops) {
      if (RegExp(r'^Chapter \d+, Shloka \d').hasMatch(tourStop.line)) {
        currentShloka++;
      }
      if (currentShloka >= 0 && tourStop.show != null) {
        final englishWords = tourStop.show!
            .where((word) => !RegExp('^[\u0900-\u097F]+').hasMatch(word) && !word.startsWith('['));
        showsForThreeShlokas[currentShloka].addAll(englishWords);
      }
    }
    GuidedTourController guidedTourController = Get.find();

    return Column(children: [
      Expanded(
          child: Row(children: [
        Expanded(flex: 2, child: CoverQuestion(feedContent.openerQs[0].value)),
        Expanded(child: CoverStop(showsForThreeShlokas[0], guidedTourController.showWordsScroller[0])),
      ])),
      Expanded(
          child: Row(children: [
        Expanded(child: CoverStop(showsForThreeShlokas[1], guidedTourController.showWordsScroller[1])),
        Expanded(flex: 2, child: CoverQuestion(feedContent.openerQs[1].value)),
      ])),
      Expanded(
          child: Row(children: [
        Expanded(flex: 2, child: CoverQuestion(feedContent.openerQs[2].value)),
        Expanded(child: CoverStop(showsForThreeShlokas[2], guidedTourController.showWordsScroller[2])),
      ])),
    ]);
  });
}

class CoverQuestion extends StatelessWidget {
  const CoverQuestion(this.openerQ, {super.key});
  final String openerQ;

  @override
  Widget build(BuildContext context) {
    return Stack(
      alignment: Alignment.center,
      children: [
        Icon(
          Icons.menu_book,
          color: contentColors(context)?.noteBackground.withAlpha(200),
          size: 128,
        ),
        Text(
          openerQ,
          style: TextStyle(
            fontSize: 24,
            color: contentColors(context)?.commentaryTextColor,
          ),
          textAlign: TextAlign.center,
        ),
      ],
    );
  }
}

class CoverStop extends StatelessWidget {
  const CoverStop(this.coverStopWords, this.scroller, {super.key});
  final List<String> coverStopWords;
  final CarouselController scroller;

  @override
  Widget build(BuildContext context) {
    return Card(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        elevation: 2,
        child: coverStopWords.isNotEmpty
            ? TourStopWords(coverStopWords, scroller)
            : Center(
                child: Text('...'),
              ));
  }
}

class TourStopWords extends StatelessWidget {
  final List<String> coverStopWords;
  final CarouselController scroller;
  const TourStopWords(this.coverStopWords, this.scroller, {super.key});

  @override
  Widget build(BuildContext context) {
    return CarouselView.weighted(
        flexWeights: [1, 3, 5, 3, 1],
        scrollDirection: Axis.vertical,
        controller: scroller,
        backgroundColor: contentColors(context)?.commentaryBackground,
        children: coverStopWords.map((word) {
          return Padding(
            padding: const EdgeInsets.symmetric(horizontal: 4),
            child: Center(
                child: Padding(
              padding: EdgeInsets.all(4),
              child: FittedBox(
                fit: BoxFit.scaleDown,
                child: Text(
                  word,
                  style: TextStyle(color: contentColors(context)?.commentaryTextColor),
                  textAlign: TextAlign.center,
                ),
              ),
            )),
          );
        }).toList());
  }
}
