import 'package:askys/content_source.dart';
import 'package:askys/feedcontent.dart';
import 'package:askys/guided_tour.dart';
import 'package:dio/dio.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:get/get.dart';
import 'package:http_mock_adapter/http_mock_adapter.dart';
import 'feed_test.mocks.dart';

const playablesTOC = '''# Playable feeds

[Bring the best in you](https://rapalearning.com/gitapower/feed/8-25.14-1.18-1.bring_the_best_in_you)
''';

void main() {
  // TODO: Remove this duplicate - it's also present in moving_subtitles
  setUp(() {
    final mockPlayer = MockAudioPlayer();
    final dio = Dio();
    final dioAdapter = DioAdapter(dio: dio);
    dioAdapter.onGet(
        '${GitHubFetcher.playablesUrl}/bring_the_best_in_you/playable.json',
        (server) => server.reply(
            200,
            '[{"line": "l1", "link": "1-1", "speech": "s1.mp3", "show": ["k11", "k12"]}, '
            '{"line": "l2", "speech": "s2.mp3"}, '
            '{"line": "l3", "speech": "s3.mp3", "link": "1-3"}]'));
    dioAdapter.onGet(
        '${GitHubFetcher.playablesUrl}/playablestoc.md', (server) => server.reply(200, playablesTOC));
    dio.httpClientAdapter = dioAdapter;
    Get.put(GitHubFetcher(dio));

    final feedContent = FeedContent.random(aPlayer: mockPlayer);
    feedContent.tour.tourStops.value = [
      TourStop('s1.mp3', 'l1', null, null),
      TourStop('s2.mp3', 'l2', '2-34.md', null),
      TourStop('s3.mp3', 'l3', 'Chapter_7.md/bhakti_a_defn', ['sho1', 'sho2']),
      TourStop('s4.mp3', 'l4', null, null),
      TourStop('s5.mp3', 'l5', null, null),
    ];
    feedContent.tourFolder = 'bring_the_best_in_you';
    feedContent.tour.playable = 'bring_the_best_in_you';
    Get.put(feedContent);
    Get.put(GuidedTourController());
  });
  testWidgets('guided tour displays the tour', (WidgetTester tester) async {
    Get.put(PlayablesTOC());
    final playable = Playable('Bring the best in you', '/gitapower/feed/8-25.14-1.18-1.bring_the_best_in_you',
        'bring_the_best_in_you');
    curateToFeed(playable);

    await tester.pumpWidget(
      GetMaterialApp(
        home: guidedTourScreen('bring_the_best_in_you'),
      ),
    );
    await tester.pumpAndSettle();
    expect(find.text('Bring the best in you'), findsOneWidget);
    expect(find.textContaining('Voice generated by AI'), findsOneWidget);

    // TODO: Verify the layout based on screen orientation
  });
  testWidgets('can tap on play only when narration is available', (tester) async {
    // TODO: Implement this test
    // when(mockPlayer.setAudioSource(any, preload: true, initialIndex: 0, initialPosition: Duration.zero))
    //     .thenAnswer((_) async {
    //   return const Duration(milliseconds: 50);
    // });
    // final ContentNotes contentNotes = Get.find();
    // contentNotes.notesLoaded.value = true;
    // await tester.pumpWidget(GetMaterialApp(
    //     home: Scaffold(body: feedScreen()), getPages: [GetPage(name: '/feed', page: () => feedScreen())]));
    // await tester.pumpAndSettle();
    // expect(find.byKey(const Key('feedplay')), findsNothing);
    // navigateApplink(Uri.parse('/gitapower/feed/2-34.9-13.15-14.bring_the_best_in_you'));
    // await tester.pumpAndSettle();
    // final player = find.byKey(const Key('feedplay'));
    // expect(player, findsOneWidget);
    // await tester.tap(player);
    // await tester.pumpAndSettle();
    // final FeedContent feedContent = Get.find();
    // expect(feedContent.tour.state.value, equals(TourState.idle));
    // verify(mockPlayer.setAudioSource(any, preload: true, initialIndex: 0, initialPosition: Duration.zero))
    //     .called(1);
    // verify(mockPlayer.play()).called(1);
    // Get.back();
    // await tester.pumpAndSettle();
    // verify(mockPlayer.stop()).called(1);
  });
  testWidgets('guides from one para to the next', (tester) async {
    // TODO: Implement this test
    // final FeedContent feedContent = Get.find();
    // feedContent.tourFolder = 'bring_the_best_in_you';
    // feedContent.tour.tourStops.value = [
    //   TourStop('s1.mp3', 'l1', null, null),
    //   TourStop('s2.mp3', 'l2', '2-34.md', null),
    //   TourStop('s3.mp3', 'l3', 'Chapter_7.md/bhakti_a_defn', ['sho1', 'sho2']),
    // ];
    // reset(mockPlayer);
    // await tester
    //     .pumpWidget(GetMaterialApp(home: const Scaffold(body: FeedPlayIcon(TourState.idle)), getPages: [
    //   GetPage(name: '/shloka/:mdFilename', page: () => const Text('mdfile')),
    //   GetPage(name: '/shloka/:mdFilename/:noteId', page: () => const Text('mdfile with nodeid')),
    // ]));
    // await tester.pumpAndSettle();
    // // Start playing
    // feedContent.tour.playState(PlayerState(true, ProcessingState.ready));
    // feedContent.tour.moveTo(2);
    // await tester.pumpAndSettle();
    // expect(Get.currentRoute, '/shloka/2-34.md');
    // feedContent.tour.moveTo(3);
    // expect(Get.currentRoute, '/shloka/Chapter_7.md/bhakti_a_defn');
  });
}
