import 'package:askys/content_source.dart';
import 'package:askys/feedcontent.dart';
import 'package:askys/guided_tour.dart';
import 'package:dio/dio.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:get/get.dart';
import 'package:http_mock_adapter/http_mock_adapter.dart';

import 'feed_test.mocks.dart';

void main() {
  // TODO: Remove this duplicate - it's also present in moving_subtitles
  setUp(() {
    final mockPlayer = MockAudioPlayer();
    final dio = Dio();
    final dioAdapter = DioAdapter(dio: dio);
    dioAdapter.onGet(
        '${GitHubFetcher.playablesUrl}/bring_the_best_in_you/playable.json',
        (server) => server.reply(
            200,
            '[{"line": "l1", "link": "1-1", "speech": "s1.mp3", "show": ["k11", "k12"]}, '
            '{"line": "l2", "speech": "s2.mp3"}, '
            '{"line": "l3", "speech": "s3.mp3", "link": "1-3"}]'));
    dio.httpClientAdapter = dioAdapter;
    Get.put(GitHubFetcher(dio));

    final feedContent = FeedContent.random(aPlayer: mockPlayer);
    feedContent.tour.tourStops.value = [
      TourStop('s1.mp3', 'l1', null, null),
      TourStop('s2.mp3', 'l2', '2-34.md', null),
      TourStop('s3.mp3', 'l3', 'Chapter_7.md/bhakti_a_defn', ['sho1', 'sho2']),
      TourStop('s4.mp3', 'l4', null, null),
      TourStop('s5.mp3', 'l5', null, null),
    ];
    feedContent.tourFolder = 'bring_the_best_in_you';
    feedContent.tour.playable = 'bring_the_best_in_you';
    Get.put(feedContent);
  });
  testWidgets('guided tour displays the tour', (WidgetTester tester) async {
    await tester.pumpWidget(
      GetMaterialApp(
        home: guidedTourScreen(),
      ),
    );
    await tester.pumpAndSettle();
    expect(find.text('Bring the best in you'), findsOneWidget);
    expect(find.textContaining('Voice generated by AI'), findsOneWidget);

    // TODO: Verify the layout based on screen orientation
  });
}
