import 'package:askys/choice_selector.dart';
import 'package:askys/content_source.dart';
import 'package:askys/feedcontent.dart';
import 'package:askys/feedplay_icon.dart';
import 'package:askys/guided_tour.dart';
import 'package:askys/notecontent.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:get/get.dart';
import 'package:http_mock_adapter/http_mock_adapter.dart';
import 'package:askys/content_actions.dart';
import 'package:askys/mdcontent.dart';

import 'feed_test.mocks.dart';
import 'package:mockito/annotations.dart';
import 'package:just_audio/just_audio.dart';
import 'package:mockito/mockito.dart';

const playablesTOC = '''# Playable feeds

[Bring the best in you](https://rapalearning.com/gitapower/feed/8-25.14-1.18-1.bring_the_best_in_you)
''';

@GenerateNiceMocks([MockSpec<AudioPlayer>()])
void main() {
  final mockPlayer = MockAudioPlayer();
  void fillTour(FeedContent feedContent) {
    feedContent.tour.tourStops.value = [
      TourStop('s1.mp3', 'l1', null, null),
      TourStop('s2.mp3', 'l2', '2-34.md', null),
      TourStop('s3.mp3', 'l3', 'Chapter_7.md/bhakti_a_defn', ['sho1', 'sho2']),
      TourStop('s4.mp3', 'l4', null, null),
      TourStop('s5.mp3', 'l5', null, null),
    ];
    feedContent.tourFolder = 'bring_the_best_in_you';
    feedContent.tour.playable = 'bring_the_best_in_you';
  }

  // TODO: Remove this duplicate - it's also present in moving_subtitles
  setUp(() {
    final dio = Dio();
    final dioAdapter = DioAdapter(dio: dio);
    dioAdapter.onGet(
        '${GitHubFetcher.playablesUrl}/bring_the_best_in_you/playable.json',
        (server) => server.reply(
            200,
            '[{"line": "l1", "link": "1-1", "speech": "s1.mp3", "show": ["k11", "k12"]}, '
            '{"line": "l2", "speech": "s2.mp3"}, '
            '{"line": "l3", "speech": "s3.mp3", "link": "1-3"}]'));
    dioAdapter.onGet(
        '${GitHubFetcher.playablesUrl}/playablestoc.md', (server) => server.reply(200, playablesTOC));
    dio.httpClientAdapter = dioAdapter;
    Get.put(GitHubFetcher(dio));

    final feedContent = FeedContent.random(aPlayer: mockPlayer);
    fillTour(feedContent);
    Get.put(feedContent);
    Get.put(Choices());
    Get.put(ContentNotes());
    Get.put(ContentActions());
    Get.put(ShowWords());
    Get.put(GuidedTourController());
  });
  testWidgets('guided tour displays the tour', (WidgetTester tester) async {
    Get.put(PlayablesTOC());
    final playable = Playable('Bring the best in you', '/gitapower/feed/8-25.14-1.18-1.bring_the_best_in_you',
        'bring_the_best_in_you');
    // TODO: Remove curateToFeed
    curateToFeed(playable);

    await tester.pumpWidget(GetMaterialApp(home: guidedTourScreen('bring_the_best_in_you')));
    await tester.pumpAndSettle();
    expect(find.text('Bring the best in you'), findsOneWidget);
    expect(find.textContaining('Voice generated by AI'), findsOneWidget);

    // TODO: Verify the layout based on screen orientation
  });
  testWidgets('tapping on play starts the narration', (tester) async {
    Get.put(PlayablesTOC());
    when(mockPlayer.setAudioSource(any, preload: true, initialIndex: 0, initialPosition: Duration.zero))
        .thenAnswer((_) async {
      return const Duration(milliseconds: 50);
    });
    final ContentNotes contentNotes = Get.find();
    contentNotes.notesLoaded.value = true;
    final FeedContent feedContent = Get.find();
    feedContent.tour.state.value = TourState.idle;
    await tester.pumpWidget(GetMaterialApp(home: guidedTourScreen('bring_the_best_in_you')));
    await tester.pumpAndSettle();
    final player = find.byKey(const Key('guided/feedplay'));
    expect(player, findsOneWidget);
    await tester.tap(player);
    await tester.pumpAndSettle();
    expect(feedContent.tour.state.value, equals(TourState.idle));
    verify(mockPlayer.setAudioSource(any, preload: true, initialIndex: 0, initialPosition: Duration.zero))
        .called(1);
    verify(mockPlayer.play()).called(1);
  });
  testWidgets('guides from one para to the next', (tester) async {
    Get.put(PlayablesTOC());
    final ContentNotes contentNotes = Get.find();
    contentNotes.notesLoaded.value = true;
    final FeedContent feedContent = Get.find();
    fillTour(feedContent);
    reset(mockPlayer);
    await tester.pumpWidget(GetMaterialApp(home: guidedTourScreen('bring_the_best_in_you')));
    await tester.pumpAndSettle();
    // Start playing
    feedContent.tour.playState(PlayerState(true, ProcessingState.ready));
    feedContent.tour.moveTo(2);
    await tester.pumpAndSettle();
    expect(find.text('2-34'), findsOneWidget);
    feedContent.tour.moveTo(3);
    await tester.pumpAndSettle();
    expect(find.text('Chapter 7'), findsOneWidget);
  });
  testWidgets('syncs with the player state', (tester) async {
    final FeedContent feedContent = Get.find();
    feedContent.tourFolder = 'bring_the_best_in_you';
    feedContent.tour.tourStops.value = [TourStop('s1.mp3', 'l1', null, null)];
    feedContent.tour.state.value = TourState.idle;
    reset(mockPlayer);
    await tester.pumpWidget(MaterialApp(home: Scaffold(body: FeedPlayIcon(key: const Key('feedplay')))));
    await tester.tap(find.byKey(const Key('feedplay')));
    await tester.pumpAndSettle();
    expect(feedContent.tour.state.value, equals(TourState.idle));
    verify(mockPlayer.play()).called(1);
    // After tapping play, it will load
    feedContent.tour.playState(PlayerState(false, ProcessingState.loading));
    expect(feedContent.tour.state.value, equals(TourState.loading));
    feedContent.tour.playState(PlayerState(false, ProcessingState.buffering));
    expect(feedContent.tour.state.value, equals(TourState.loading));
    // While loading, tapping should not result in another play
    reset(mockPlayer);
    await tester.tap(find.byKey(const Key('feedplay')));
    await tester.pumpAndSettle();
    verifyNever(mockPlayer.play());
    // After loading, it starts playing
    feedContent.tour.playState(PlayerState(true, ProcessingState.ready));
    expect(feedContent.tour.state.value, equals(TourState.playing));
    // Tapping while playing must pause
    await tester.tap(find.byKey(const Key('feedplay')));
    await tester.pumpAndSettle();
    verify(mockPlayer.pause()).called(1);
    feedContent.tour.playState(PlayerState(false, ProcessingState.ready));
    expect(feedContent.tour.state.value, equals(TourState.paused));
    // Tapping on pause must play again, without reloading
    await tester.tap(find.byKey(const Key('feedplay')));
    await tester.pumpAndSettle();
    verify(mockPlayer.play()).called(1);
    verifyNever(mockPlayer.setAudioSource(any,
        preload: anyNamed('preload'),
        initialIndex: anyNamed('initialIndex'),
        initialPosition: anyNamed('initialPosition')));
    // Finally it completes
    feedContent.tour.playState(PlayerState(true, ProcessingState.completed));
    expect(feedContent.tour.state.value, equals(TourState.idle));
  });
  testWidgets('clicking on a page goes to the shloka', (tester) async {
    Get.put(PlayablesTOC());
    final ContentNotes contentNotes = Get.find();
    contentNotes.notesLoaded.value = true;
    final FeedContent feedContent = Get.find();
    fillTour(feedContent);
    reset(mockPlayer);
    await tester.pumpWidget(GetMaterialApp(
      home: guidedTourScreen('bring_the_best_in_you'),
      getPages: [GetPage(name: '/shloka/2-34.md', page: () => const Text('2-34'))],
    ));
    await tester.pumpAndSettle();
    // Start playing
    feedContent.tour.playState(PlayerState(true, ProcessingState.ready));
    feedContent.tour.moveTo(2);
    await tester.pumpAndSettle();
    await tester.tap(find.text('2-34'));
    await tester.pumpAndSettle();
    expect(Get.currentRoute, equals('/shloka/2-34.md'));
  });
}
