name: Flutter to apk

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: setup flutter
      uses: subosito/flutter-action@v2
    - run: flutter --version
    - name: get dependencies
      working-directory: ./feeder
      run: flutter pub get

    - name: setup key
      working-directory: ./feeder
      run: echo "${{ secrets.KEY_JKS }}" | base64 -d > android/app/keystore.jks

    - name: setup offline content
      working-directory: ./feeder
      run: bash gita-begin-offline.sh

    - name: build release apk
      working-directory: ./feeder
      env: 
        JKS_PASSWORD: ${{ secrets.JKS_PASSWORD }}
      run: |
        echo "Building ${GITHUB_REF##*/}"
        flutter build apk --release --build-name ${GITHUB_REF##*/} --build-number ${{ github.run_number }}

    - name: upload apk
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: feeder/build/app/outputs/apk/release/app-release.apk
        retention-days: 3
