name: Flutter to apk

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: setup flutter
      uses: subosito/flutter-action@v2

    - name: get dependencies
      working-directory: ./feeder
      run: flutter pub get

    - name: build release apk
      working-directory: ./feeder
      run: flutter build apk --release

    - name: upload apk
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: feeder/build/app/outputs/apk/release/app-release.apk
        retention-days: 3
