name: Flutter to apk

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: setup flutter
      uses: subosito/flutter-action@v2
    - run: flutter --version
    - name: get dependencies
      working-directory: ./feeder
      run: flutter pub get

    - name: setup key
      working-directory: ./feeder
      run: echo "${{ secrets.KEY_JKS }}" | base64 -d > android/app/keystore.jks

    - name: setup offline content
      working-directory: ./feeder
      run: bash gita-begin-offline.sh

    - name: say the version information
      run: sed -i "s/555/${GITHUB_REF##*/}-${{ github.run_number }}/g" feeder/lib/build_ident_widget.dart

    - name: build release apk
      working-directory: ./feeder
      env: 
        JKS_PASSWORD: ${{ secrets.JKS_PASSWORD }}
      run: |
        echo "Building ${GITHUB_REF##*/}"
        flutter build appbundle --release --build-name ${GITHUB_REF##*/} --build-number ${{ github.run_number }}
        rm android/app/keystore.jks
        ls -al build/app/outputs/bundle/release/

    - name: upload appbundle
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: feeder/build/app/outputs/bundle/release/app-release.aab
        retention-days: 3

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        working-directory: ./feeder
        api-level: 29
        script: flutter drive --driver=test_driver/screenshot_driver.dart --target=integration_test/integ_test.dart

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots-${{ github.run_number }}
        path: feeder/screenshots

    - name: Update screenshots for Fastlane
      working-directory: ./feeder
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash screenshots-to-fastlane.sh
        git config --global user.email "sudeep@rapalearning.com"
        git config --global user.name "GitaPower builder workflow"
        git checkout -b see-screens-${{ github.run_number }}
        git add ./android/fastlane/metadata/android/en-US/images/phoneScreenshots/*
        git commit -m "update screenshots"
        git push --set-upstream origin see-screens-${{ github.run_number }}
        gh pr create --title "Snaps from ${GITHUB_REF}" --body "For Fastlane internal ${{ github.run_number }}"

    - name: Set up Ruby for Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true

    - name: Install Fastlane
      run: gem install fastlane

    - name: Upload to internal track
      env:
        GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
      run: |
        cd feeder/android
        mkdir -p ./.google-play
        echo "$GOOGLE_PLAY_JSON_KEY" > ./.google-play/gitapower-service-account.json
        fastlane to_internal_testing
