name: Flutter checkmycode

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: setup flutter
      uses: subosito/flutter-action@v2
    - name: get dependencies
      working-directory: ./feeder
      run: flutter pub get
    - name: format
      working-directory: ./feeder
      run: flutter format --set-exit-if-changed .
    - name: checkmycode
      working-directory: ./feeder
      run: bash checkmycode.sh
