name: compile headers

on: workflow_dispatch

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: setup flutter
      uses: subosito/flutter-action@v2

    - name: get dependencies
      working-directory: ./feeder
      run: flutter pub get

    - name: generate headers
      working-directory: ./feeder/tools
      run: bash generate_headers.sh

    - name: commit in branch
      run: |
        git checkout -b compile-shloka-headers
        git add .
        git commit -m "shloka headers"
        git push
        
